dep_parse: !Experiment
  exp_global: !ExpGlobal
    model_file: '{EXP_DIR}/models/{EXP}.mod'
    log_file: '{EXP_DIR}/logs/{EXP}.log'
    default_layer_dim: 512
    dropout: 0.3
  # model architecture
  model: !TreeTranslator
    src_embedder: !DenseWordEmbedder {}
    src_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: examples/data/head.en.vocab}
    trg_reader: !CoNLLToRNNGActionsReader
      surface_vocab: !Vocab
        vocab_file: examples/data/parse/head.en.vocab
      edg_vocab: !Vocab
        vocab_file: examples/data/parse/head.en.edge_vocab
      nt_vocab: !Vocab
        vocab_file: examples/data/parse/head.en.node_vocab
    encoder: !IdentitySeqTransducer {}
    decoder: !RNNGDecoder
      rnn: !UniLSTMSeqTransducer
        decoder_input_feeding: false
      bridge: !NoBridge {}
      term_scorer: !Softmax
        vocab: !Ref { path: model.trg_reader.surface_vocab }
        output_projector: !Ref {path: model.src_embedder}
      head_composer: !DyerHeadComposer
        fwd_combinator: !UniLSTMSeqTransducer
          decoder_input_feeding: false
        bwd_combinator: !UniLSTMSeqTransducer
          decoder_input_feeding: false
  # training parameters
  train: !SimpleTrainingRegimen
    batcher: !SrcBatcher
      batch_size: 1
    trainer: !AdamTrainer
      alpha: 0.001
    run_for_epochs: 20
    src_file: examples/data/head.en
    trg_file: examples/data/parse/head.en.conll
    dev_tasks:
      - !LossEvalTask
        src_file: examples/data/head.en
        ref_file: examples/data/parse/head.en.conll
        # final evaluation
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: rnng_parse_fmeasure
      src_file: examples/data/head.en
      hyp_file: examples/output/{EXP}.test_hyp
      ref_file: examples/data/parse/head.en.rnng_actions
      inference: !AutoRegressiveInference
        search_strategy: !BeamSearch {}
